services:
  - type: web
    name: coworking-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: VERIFICATION_PASSWORD
        sync: false
      - key: WEBHOOK_HOST
        # Render автоматически дает домен, но его нужно прописать в Variables или через $RENDER_EXTERNAL_URL 
        value: https://ваше-имя-в-render.onrender.com